=== Gekctek/ic-inspector/src/services/stubs/message.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/MessageEntry",
  "definitions": {
      "MessageEntry": {
          "type": "object",
          "properties": {
              "meta": {
                  "type": "object",
                  "properties": {
                      "originalRequestId": {
                          "$ref": "#/definitions/MessageId"
                      },
                      "type": {
                          "type": "string",
                          "enum": [
                              "update",
                              "query"
                          ]
                      },
                      "status": {
                          "$ref": "#/definitions/MessageStatus"
                      },
                      "consensus": {
                          "type": "boolean"
                      },
                      "verified": {
                          "type": "null"
                      },
                      "boundary": {
                        "$ref": "#/definitions/URL"
                      }
                  },
                  "required": [
                      "originalRequestId",
                      "type",
                      "status",
                      "consensus",
                      "verified",
                      "boundary"
                  ],
                  "additionalProperties": false
              },
              "canister": {
                  "type": "object",
                  "properties": {
                      "identifier": {
                          "type": "string"
                      },
                      "name": {
                          "type": "string"
                      },
                      "url": {
                          "type": "string"
                      },
                      "description": {
                          "type": "string"
                      },
                      "logoUrl": {
                          "type": "string"
                      },
                      "subnet": {
                          "type": "string"
                      },
                      "moduleHash": {
                          "type": "string"
                      },
                      "controllers": {
                          "type": "array",
                          "items": {
                              "type": "string"
                          }
                      }
                  },
                  "required": [
                      "identifier",
                      "subnet",
                      "moduleHash",
                      "controllers"
                  ],
                  "additionalProperties": false
              },
              "method": {
                  "type": "object",
                  "properties": {
                      "name": {
                          "type": "string"
                      },
                      "query": {
                          "type": "boolean"
                      }
                  },
                  "required": [
                      "name",
                      "query"
                  ],
                  "additionalProperties": false
              },
              "caller": {
                  "type": "object",
                  "properties": {
                      "identifier": {
                          "type": "string"
                      },
                      "isAnonymous": {
                          "type": "boolean"
                      }
                  },
                  "required": [
                      "identifier",
                      "isAnonymous"
                  ],
                  "additionalProperties": false
              },
              "timing": {
                  "type": "object",
                  "properties": {
                      "timestamp": {
                          "type": "string"
                      },
                      "durationMs": {
                          "type": "number"
                      },
                      "requestCount": {
                          "type": "number"
                      }
                  },
                  "required": [
                      "timestamp",
                      "requestCount"
                  ],
                  "additionalProperties": false
              },
              "requests": {
                  "type": "object",
                  "patternProperties": {
                      "^[a-fA-F0-9]+$": {
                      "type": "object",
                      "properties": {
                          "meta": {
                              "type": "object",
                              "properties": {
                                  "requestId": {
                                      "type": "string"
                                  },
                                  "originalRequestId": {
                                      "$ref": "#/definitions/MessageId"
                                  },
                                  "type": {
                                      "$ref": "#/definitions/RequestType"
                                  },
                                  "boundary": {
                                    "$ref": "#/definitions/URL"
                                  }
                              },
                              "required": [
                                  "requestId",
                                  "originalRequestId",
                                  "type",
                                  "boundary"
                              ],
                              "additionalProperties": false
                          },
                          "caller": {
                              "type": "object",
                              "properties": {
                                  "identifier": {
                                      "type": "string"
                                  },
                                  "isAnonymous": {
                                      "type": "boolean"
                                  }
                              },
                              "required": [
                                  "identifier",
                                  "isAnonymous"
                              ],
                              "additionalProperties": false
                          },
                          "canister": {
                              "type": "object",
                              "properties": {
                                  "identifier": {
                                      "type": "string"
                                  },
                                  "name": {
                                      "type": "string"
                                  },
                                  "url": {
                                      "type": "string"
                                  },
                                  "description": {
                                      "type": "string"
                                  },
                                  "logoUrl": {
                                      "type": "string"
                                  },
                                  "subnet": {
                                      "type": "string"
                                  },
                                  "moduleHash": {
                                      "type": "string"
                                  },
                                  "controllers": {
                                      "type": "array",
                                      "items": {
                                          "type": "string"
                                      }
                                  }
                              },
                              "required": [
                                  "identifier",
                                  "subnet",
                                  "moduleHash",
                                  "controllers"
                              ],
                              "additionalProperties": false
                          },
                          "method": {
                              "type": "object",
                              "properties": {
                                  "name": {
                                      "type": "string"
                                  },
                                  "query": {
                                      "type": "boolean"
                                  }
                              },
                              "required": [
                                  "name",
                                  "query"
                              ],
                              "additionalProperties": false
                          },
                          "timing": {
                              "type": "object",
                              "properties": {
                                  "timestamp": {
                                      "type": "string"
                                  },
                                  "durationMs": {
                                      "type": "number"
                                  }
                              },
                              "required": [
                                  "timestamp"
                              ],
                              "additionalProperties": false
                          },
                          "request": {
                              "$ref": "#/definitions/DecodedRequest"
                          },
                          "response": {
                              "$ref": "#/definitions/DecodedResponse"
                          }
                      },
                      "required": [
                          "meta",
                          "caller",
                          "canister",
                          "method",
                          "timing",
                          "request",
                          "response"
                      ],
                      "additionalProperties": false
                    }
                  }
              }
          },
          "required": [
              "meta",
              "canister",
              "method",
              "caller",
              "timing",
              "requests"
          ],
          "additionalProperties": false
      },
      "MessageId": {
          "type": "string"
      },
      "MessageStatus": {
          "type": "string",
          "enum": [
              "pending",
              "replied",
              "rejected"
          ]
      },
      "RequestType": {
          "type": "string",
          "enum": [
              "query",
              "call",
              "read_state"
          ]
      },
      "DecodedRequest": {
          "anyOf": [
              {
                  "type": "object",
                  "properties": {
                      "message": {
                          "type": "string"
                      },
                      "requestId": {
                          "type": "string"
                      },
                      "canisterId": {
                          "type": "string"
                      },
                      "method": {
                          "type": "string"
                      },
                      "sender": {
                          "$ref": "#/definitions/Principal"
                      },
                      "requestType": {
                          "$ref": "#/definitions/RequestType"
                      },
                      "ingressExpiry": {
                          "$ref": "#/definitions/Expiry"
                      },
                      "boundary": {
                        "$ref": "#/definitions/URL"
                      },
                      "paths": {
                          "type": "array",
                          "items": {
                              "type": "array",
                              "items": {
                                  "type": "object",
                                  "patternProperties": {
                                      "[0-9]+": {
                                          "type": "number"
                                      }
                                  }
                              }
                          }
                      }
                  },
                  "required": [
                      "boundary",
                      "canisterId",
                      "ingressExpiry",
                      "message",
                      "method",
                      "paths",
                      "requestId",
                      "requestType",
                      "sender"
                  ],
                  "additionalProperties": false
              },
              {
                  "$ref": "#/definitions/DecodedReadRequest"
              }
          ]
      },
      "Principal": {
          "type": "object",
          "properties": {
            "_stub": { "type": "boolean" },
            "_principal": { "type": "boolean" },
            "val": { "type": "string" }
          },
          "required": [ "_stub", "_principal", "val"]
        },
      "Expiry": {
          "type": "object",
          "properties": {
            "_stub": { "type": "boolean" },
            "_bigint": { "type": "boolean" },
            "val": { "type": "string" }
          },
          "required": [ "_stub", "_bigint", "val" ]
        },
      "URL": {
          "type": "object",
          "properties": {
            "_stub": { "type": "boolean" },
            "_url": { "type": "boolean" },
            "val": { "type": "string" }
          },
          "required": [ "_stub", "_url", "val" ]
        },
      "DecodedReadRequest": {
          "type": "object",
          "properties": {
              "message": {
                  "type": "string"
              },
              "requestId": {
                  "type": "string"
              },
              "canisterId": {
                  "type": "string"
              },
              "method": {
                  "type": "string"
              },
              "sender": {
                  "$ref": "#/definitions/Principal"
              },
              "requestType": {
                  "$ref": "#/definitions/RequestType"
              },
              "ingressExpiry": {
                  "$ref": "#/definitions/Expiry"
              },
              "boundary": {
                "$ref": "#/definitions/URL"
              },
              "args": {
                  "type": "object",
                  "properties": {
                      "result": {},
                      "withInterface": {
                          "type": "boolean"
                      }
                  },
                  "required": [
                      "result",
                      "withInterface"
                  ],
                  "additionalProperties": false
              }
          },
          "required": [
              "args",
              "boundary",
              "canisterId",
              "ingressExpiry",
              "message",
              "method",
              "requestId",
              "requestType",
              "sender"
          ],
          "additionalProperties": false
      },
      "DecodedResponse": {
          "anyOf": [
              {
                  "type": "object",
                  "properties": {
                      "status": {
                          "$ref": "#/definitions/QueryResponseStatus"
                      }
                  },
                  "required": [
                      "status"
                  ],
                  "additionalProperties": false
              },
              {
                  "type": "object",
                  "properties": {
                      "status": {
                          "$ref": "#/definitions/QueryResponseStatus"
                      },
                      "reply": {
                          "$ref": "#/definitions/CandidDecodeResult"
                      }
                  },
                  "required": [
                      "reply",
                      "status"
                  ],
                  "additionalProperties": false
              },
              {
                  "type": "object",
                  "properties": {
                      "status": {
                          "$ref": "#/definitions/RequestStatusResponseStatus"
                      }
                  },
                  "required": [
                      "status"
                  ],
                  "additionalProperties": false
              },
              {
                  "type": "object",
                  "properties": {
                      "status": {
                          "$ref": "#/definitions/RequestStatusResponseStatus"
                      },
                      "reply": {
                          "$ref": "#/definitions/CandidDecodeResult"
                      }
                  },
                  "required": [
                      "reply",
                      "status"
                  ],
                  "additionalProperties": false
              },
              {
                  "$ref": "#/definitions/RejectedResponse"
              }
          ]
      },
      "QueryResponseStatus": {
          "type": "string",
          "enum": [
              "replied",
              "rejected"
          ]
      },
      "CandidDecodeResult": {
          "type": "object",
          "properties": {
              "result": {},
              "withInterface": {
                  "type": "boolean"
              }
          },
          "required": [
              "result",
              "withInterface"
          ],
          "additionalProperties": false
      },
      "RequestStatusResponseStatus": {
          "type": "string",
          "enum": [
              "received",
              "processing",
              "replied",
              "rejected",
              "unknown",
              "done"
          ]
      },
      "RejectedResponse": {
          "type": "object",
          "properties": {
              "status": {
                  "$ref": "#/definitions/QueryResponseStatus"
              },
              "message": {
                  "type": "string"
              },
              "code": {
                  "type": "number"
              }
          },
          "required": [
              "code",
              "message",
              "status"
          ],
          "additionalProperties": false
      }
  }
}

=== Gekctek/ic-inspector/src/stubs/metascore.getGames.json
{
  "caller": {
    "identifier": "2vxsx-fae",
    "isAnonymous": true
  },
  "canister": {
    "identifier": "tzvxm-jqaaa-aaaaj-qabga-cai",
    "subnet": "jtdsg-3h6gi-hs7o5-z2soi-43w3z-soyl3-ajnp3-ekni5-sw553-5kw67-nqe",
    "moduleHash": "5ac0453ff6787f7c5670e8bb55b5ddeb54ae6cec07ac1e9a95aee86b44988c04",
    "controllers": [
      "tmsgb-iyaaa-aaaaj-qabfq-cai"
    ]
  },
  "meta": {
    "originalRequestId": "c688dc38f346ae40f6ed5f8a8b13c0fbd6876b3f215ed95563738a3c6bc5795b",
    "type": "query",
    "status": "replied",
    "consensus": false,
    "verified": null,
    "boundary": {
      "_stub": true,
      "_url": true,
      "val": "https://raw.ic0.app/api/v2/canister/tzvxm-jqaaa-aaaaj-qabga-cai/query"
    }
  },
  "method": {
    "name": "getGames",
    "query": true
  },
  "timing": {
    "timestamp": "2022-08-16T16:29:42.087Z",
    "requestCount": 1
  },
  "requests": {
    "c688dc38f346ae40f6ed5f8a8b13c0fbd6876b3f215ed95563738a3c6bc5795b": {
      "caller": {
        "identifier": "2vxsx-fae",
        "isAnonymous": true
      },
      "method": {
        "name": "getGames",
        "query": true
      },
      "canister": {
        "identifier": "tzvxm-jqaaa-aaaaj-qabga-cai",
        "subnet": "jtdsg-3h6gi-hs7o5-z2soi-43w3z-soyl3-ajnp3-ekni5-sw553-5kw67-nqe",
        "moduleHash": "5ac0453ff6787f7c5670e8bb55b5ddeb54ae6cec07ac1e9a95aee86b44988c04",
        "controllers": [
          "tmsgb-iyaaa-aaaaj-qabfq-cai"
        ]
      },
      "meta": {
        "originalRequestId": "c688dc38f346ae40f6ed5f8a8b13c0fbd6876b3f215ed95563738a3c6bc5795b",
        "requestId": "c688dc38f346ae40f6ed5f8a8b13c0fbd6876b3f215ed95563738a3c6bc5795b",
        "type": "query",
        "boundary": {
          "_stub": true,
          "_url": true,
          "val": "https://raw.ic0.app/api/v2/canister/tzvxm-jqaaa-aaaaj-qabga-cai/query"
        }
      },
      "timing": {
        "timestamp": "2022-08-16T16:29:42.087Z"
      },
      "request": {
        "boundary": {
          "_stub": true,
          "_url": true,
          "val": "https://raw.ic0.app/api/v2/canister/tzvxm-jqaaa-aaaaj-qabga-cai/query"
        },
        "message": "c688dc38f346ae40f6ed5f8a8b13c0fbd6876b3f215ed95563738a3c6bc5795b",
        "requestId": "c688dc38f346ae40f6ed5f8a8b13c0fbd6876b3f215ed95563738a3c6bc5795b",
        "sender": {
          "_stub": true,
          "_principal": true,
          "val": "2vxsx-fae"
        },
        "requestType": "query",
        "ingressExpiry": {
          "_stub": true,
          "_bigint": true,
          "val": "1660667619244000000"
        },
        "canisterId": "tzvxm-jqaaa-aaaaj-qabga-cai",
        "method": "getGames",
        "args": {
          "result": null,
          "withInterface": true
        }
      },
      "response": {
        "status": "replied",
        "reply": {
          "result": [
            [
              {
                "_stub": true,
                "_principal": true,
                "val": "qxd6u-vqaaa-aaaah-qbpcq-cai"
              },
              {
                "name": "Reversi",
                "playUrl": "https://q6avi-dyaaa-aaaah-qbpda-cai.raw.ic0.app/",
                "flavorText": [
                  "A multiplayer reversi game."
                ]
              }
            ],
            [
              {
                "_stub": true,
                "_principal": true,
                "val": "c6dch-iiaaa-aaaah-qacxq-cai"
              },
              {
                "name": "Dots",
                "playUrl": "https://2kvgp-zyaaa-aaaai-aappq-cai.raw.ic0.app/",
                "flavorText": [
                  "Eehm... just snake? And a few dots here and there."
                ]
              }
            ]
          ],
          "withInterface": true
        }
      }
    }
  }
}

=== Gekctek/ic-inspector/src/services/stubs/distrikt.getFollowCounts.json
{
    "caller": {
      "identifier": "mr2uc-ob4zm-yik2z-vbsny-qsj2h-2np4i-drw75-7seho-a6jjx-5stsu-fqe",
      "isAnonymous": false
    },
    "canister": {
      "identifier": "cea4l-ryaaa-aaaae-aaa6a-cai",
      "subnet": "shefu-t3kr5-t5q3w-mqmdq-jabyv-vyvtf-cyyey-3kmo4-toyln-emubw-4qe",
      "moduleHash": "cfbc6e42e626947d7cf5b7976d58422c0cdf3e5c04c4d1e31384343cb0b6145f",
      "controllers": [
        "hy3go-2qaaa-aaaae-aaabq-cai",
        "ins6m-vyaaa-aaaag-qabuq-cai",
        "xo4am-ryaaa-aaaai-qh4va-cai",
        "ho5nh-4iaaa-aaaaj-aaipa-cai",
        "vi77x-kqaaa-aaaak-aadyq-cai",
        "zheur-rqaaa-aaaal-qanoq-cai",
        "ljmf3-4iaaa-aaaan-qaafq-cai",
        "auw2h-nsumg-eq552-wz7u7-ckc2l-teo22-wjsea-gsprn-kk6ln-rofyd-bqe"
      ]
    },
    "meta": {
      "originalRequestId": "afddfc217b38f2f2ad4cd4893bd03fbc10a43c4bce015d025ae0f51493a5b851",
      "type": "query",
      "status": "replied",
      "consensus": false,
      "verified": null,
      "boundary": {
        "_stub": true,
        "_url": true,
        "val": "https://boundary.ic0.app/api/v2/canister/cea4l-ryaaa-aaaae-aaa6a-cai/query"
      }
    },
    "method": {
      "name": "getFollowCounts",
      "query": true
    },
    "timing": {
      "timestamp": "2022-08-16T04:13:45.507Z",
      "requestCount": 1
    },
    "requests": {
      "afddfc217b38f2f2ad4cd4893bd03fbc10a43c4bce015d025ae0f51493a5b851": {
        "caller": {
          "identifier": "mr2uc-ob4zm-yik2z-vbsny-qsj2h-2np4i-drw75-7seho-a6jjx-5stsu-fqe",
          "isAnonymous": false
        },
        "method": {
          "name": "getFollowCounts",
          "query": true
        },
        "canister": {
          "identifier": "cea4l-ryaaa-aaaae-aaa6a-cai",
          "subnet": "shefu-t3kr5-t5q3w-mqmdq-jabyv-vyvtf-cyyey-3kmo4-toyln-emubw-4qe",
          "moduleHash": "cfbc6e42e626947d7cf5b7976d58422c0cdf3e5c04c4d1e31384343cb0b6145f",
          "controllers": [
            "hy3go-2qaaa-aaaae-aaabq-cai",
            "ins6m-vyaaa-aaaag-qabuq-cai",
            "xo4am-ryaaa-aaaai-qh4va-cai",
            "ho5nh-4iaaa-aaaaj-aaipa-cai",
            "vi77x-kqaaa-aaaak-aadyq-cai",
            "zheur-rqaaa-aaaal-qanoq-cai",
            "ljmf3-4iaaa-aaaan-qaafq-cai",
            "auw2h-nsumg-eq552-wz7u7-ckc2l-teo22-wjsea-gsprn-kk6ln-rofyd-bqe"
          ]
        },
        "meta": {
          "originalRequestId": "afddfc217b38f2f2ad4cd4893bd03fbc10a43c4bce015d025ae0f51493a5b851",
          "requestId": "afddfc217b38f2f2ad4cd4893bd03fbc10a43c4bce015d025ae0f51493a5b851",
          "type": "query",
          "boundary": {
            "_stub": true,
            "_url": true,
            "val": "https://boundary.ic0.app/api/v2/canister/cea4l-ryaaa-aaaae-aaa6a-cai/query"
          }
        },
        "timing": {
          "timestamp": "2022-08-16T04:13:45.507Z"
        },
        "request": {
          "boundary": {
            "_stub": true,
            "_url": true,
            "val": "https://boundary.ic0.app/api/v2/canister/cea4l-ryaaa-aaaae-aaa6a-cai/query"
          },
          "message": "afddfc217b38f2f2ad4cd4893bd03fbc10a43c4bce015d025ae0f51493a5b851",
          "requestId": "afddfc217b38f2f2ad4cd4893bd03fbc10a43c4bce015d025ae0f51493a5b851",
          "sender": {
            "_stub": true,
            "_principal": true,
            "val": "mr2uc-ob4zm-yik2z-vbsny-qsj2h-2np4i-drw75-7seho-a6jjx-5stsu-fqe"
          },
          "requestType": "query",
          "ingressExpiry": {
            "_stub": true,
            "_bigint": true,
            "val": "1660623462958000000"
          },
          "canisterId": "cea4l-ryaaa-aaaae-aaa6a-cai",
          "method": "getFollowCounts",
          "args": {
            "result": [
              {
                "_stub": true,
                "_bigint": true,
                "val": "37921049911771137"
              }
            ],
            "withInterface": false
          }
        },
        "response": {
          "status": "replied",
          "reply": {
            "result": [
              {
                "_2037573648_": {
                  "_stub": true,
                  "_bigint": true,
                  "val": "33"
                },
                "_3407360661_": {
                  "_stub": true,
                  "_bigint": true,
                  "val": "135"
                }
              }
            ],
            "withInterface": false
          }
        }
      }
    }
  }
