=== Gekctek/ic-inspector/src/services/stubs/message.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/MessageEntry",
  "definitions": {
      "MessageEntry": {
          "type": "object",
          "properties": {
              "meta": {
                  "type": "object",
                  "properties": {
                      "originalRequestId": {
                          "$ref": "#/definitions/MessageId"
                      },
                      "type": {
                          "type": "string",
                          "enum": [
                              "update",
                              "query"
                          ]
                      },
                      "status": {
                          "$ref": "#/definitions/MessageStatus"
                      },
                      "consensus": {
                          "type": "boolean"
                      },
                      "verified": {
                          "type": "null"
                      },
                      "boundary": {
                        "$ref": "#/definitions/URL"
                      }
                  },
                  "required": [
                      "originalRequestId",
                      "type",
                      "status",
                      "consensus",
                      "verified",
                      "boundary"
                  ],
                  "additionalProperties": false
              },
              "canister": {
                  "type": "object",
                  "properties": {
                      "identifier": {
                          "type": "string"
                      },
                      "name": {
                          "type": "string"
                      },
                      "url": {
                          "type": "string"
                      },
                      "description": {
                          "type": "string"
                      },
                      "logoUrl": {
                          "type": "string"
                      },
                      "subnet": {
                          "type": "string"
                      },
                      "moduleHash": {
                          "type": "string"
                      },
                      "controllers": {
                          "type": "array",
                          "items": {
                              "type": "string"
                          }
                      }
                  },
                  "required": [
                      "identifier",
                      "subnet",
                      "moduleHash",
                      "controllers"
                  ],
                  "additionalProperties": false
              },
              "method": {
                  "type": "object",
                  "properties": {
                      "name": {
                          "type": "string"
                      },
                      "query": {
                          "type": "boolean"
                      }
                  },
                  "required": [
                      "name",
                      "query"
                  ],
                  "additionalProperties": false
              },
              "caller": {
                  "type": "object",
                  "properties": {
                      "identifier": {
                          "type": "string"
                      },
                      "isAnonymous": {
                          "type": "boolean"
                      }
                  },
                  "required": [
                      "identifier",
                      "isAnonymous"
                  ],
                  "additionalProperties": false
              },
              "timing": {
                  "type": "object",
                  "properties": {
                      "timestamp": {
                          "type": "string"
                      },
                      "durationMs": {
                          "type": "number"
                      },
                      "requestCount": {
                          "type": "number"
                      }
                  },
                  "required": [
                      "timestamp",
                      "requestCount"
                  ],
                  "additionalProperties": false
              },
              "requests": {
                  "type": "object",
                  "patternProperties": {
                      "^[a-fA-F0-9]+$": {
                      "type": "object",
                      "properties": {
                          "meta": {
                              "type": "object",
                              "properties": {
                                  "requestId": {
                                      "type": "string"
                                  },
                                  "originalRequestId": {
                                      "$ref": "#/definitions/MessageId"
                                  },
                                  "type": {
                                      "$ref": "#/definitions/RequestType"
                                  },
                                  "boundary": {
                                    "$ref": "#/definitions/URL"
                                  }
                              },
                              "required": [
                                  "requestId",
                                  "originalRequestId",
                                  "type",
                                  "boundary"
                              ],
                              "additionalProperties": false
                          },
                          "caller": {
                              "type": "object",
                              "properties": {
                                  "identifier": {
                                      "type": "string"
                                  },
                                  "isAnonymous": {
                                      "type": "boolean"
                                  }
                              },
                              "required": [
                                  "identifier",
                                  "isAnonymous"
                              ],
                              "additionalProperties": false
                          },
                          "canister": {
                              "type": "object",
                              "properties": {
                                  "identifier": {
                                      "type": "string"
                                  },
                                  "name": {
                                      "type": "string"
                                  },
                                  "url": {
                                      "type": "string"
                                  },
                                  "description": {
                                      "type": "string"
                                  },
                                  "logoUrl": {
                                      "type": "string"
                                  },
                                  "subnet": {
                                      "type": "string"
                                  },
                                  "moduleHash": {
                                      "type": "string"
                                  },
                                  "controllers": {
                                      "type": "array",
                                      "items": {
                                          "type": "string"
                                      }
                                  }
                              },
                              "required": [
                                  "identifier",
                                  "subnet",
                                  "moduleHash",
                                  "controllers"
                              ],
                              "additionalProperties": false
                          },
                          "method": {
                              "type": "object",
                              "properties": {
                                  "name": {
                                      "type": "string"
                                  },
                                  "query": {
                                      "type": "boolean"
                                  }
                              },
                              "required": [
                                  "name",
                                  "query"
                              ],
                              "additionalProperties": false
                          },
                          "timing": {
                              "type": "object",
                              "properties": {
                                  "timestamp": {
                                      "type": "string"
                                  },
                                  "durationMs": {
                                      "type": "number"
                                  }
                              },
                              "required": [
                                  "timestamp"
                              ],
                              "additionalProperties": false
                          },
                          "request": {
                              "$ref": "#/definitions/DecodedRequest"
                          },
                          "response": {
                              "$ref": "#/definitions/DecodedResponse"
                          }
                      },
                      "required": [
                          "meta",
                          "caller",
                          "canister",
                          "method",
                          "timing",
                          "request",
                          "response"
                      ],
                      "additionalProperties": false
                    }
                  }
              }
          },
          "required": [
              "meta",
              "canister",
              "method",
              "caller",
              "timing",
              "requests"
          ],
          "additionalProperties": false
      },
      "MessageId": {
          "type": "string"
      },
      "MessageStatus": {
          "type": "string",
          "enum": [
              "pending",
              "replied",
              "rejected"
          ]
      },
      "RequestType": {
          "type": "string",
          "enum": [
              "query",
              "call",
              "read_state"
          ]
      },
      "DecodedRequest": {
          "anyOf": [
              {
                  "type": "object",
                  "properties": {
                      "message": {
                          "type": "string"
                      },
                      "requestId": {
                          "type": "string"
                      },
                      "canisterId": {
                          "type": "string"
                      },
                      "method": {
                          "type": "string"
                      },
                      "sender": {
                          "$ref": "#/definitions/Principal"
                      },
                      "requestType": {
                          "$ref": "#/definitions/RequestType"
                      },
                      "ingressExpiry": {
                          "$ref": "#/definitions/Expiry"
                      },
                      "boundary": {
                        "$ref": "#/definitions/URL"
                      },
                      "paths": {
                          "type": "array",
                          "items": {
                              "type": "array",
                              "items": {
                                  "type": "object",
                                  "patternProperties": {
                                      "[0-9]+": {
                                          "type": "number"
                                      }
                                  }
                              }
                          }
                      }
                  },
                  "required": [
                      "boundary",
                      "canisterId",
                      "ingressExpiry",
                      "message",
                      "method",
                      "paths",
                      "requestId",
                      "requestType",
                      "sender"
                  ],
                  "additionalProperties": false
              },
              {
                  "$ref": "#/definitions/DecodedReadRequest"
              }
          ]
      },
      "Principal": {
          "type": "object",
          "properties": {
            "_stub": { "type": "boolean" },
            "_principal": { "type": "boolean" },
            "val": { "type": "string" }
          },
          "required": [ "_stub", "_principal", "val"]
        },
      "Expiry": {
          "type": "object",
          "properties": {
            "_stub": { "type": "boolean" },
            "_bigint": { "type": "boolean" },
            "val": { "type": "string" }
          },
          "required": [ "_stub", "_bigint", "val" ]
        },
      "URL": {
          "type": "object",
          "properties": {
            "_stub": { "type": "boolean" },
            "_url": { "type": "boolean" },
            "val": { "type": "string" }
          },
          "required": [ "_stub", "_url", "val" ]
        },
      "DecodedReadRequest": {
          "type": "object",
          "properties": {
              "message": {
                  "type": "string"
              },
              "requestId": {
                  "type": "string"
              },
              "canisterId": {
                  "type": "string"
              },
              "method": {
                  "type": "string"
              },
              "sender": {
                  "$ref": "#/definitions/Principal"
              },
              "requestType": {
                  "$ref": "#/definitions/RequestType"
              },
              "ingressExpiry": {
                  "$ref": "#/definitions/Expiry"
              },
              "boundary": {
                "$ref": "#/definitions/URL"
              },
              "args": {
                  "type": "object",
                  "properties": {
                      "result": {},
                      "withInterface": {
                          "type": "boolean"
                      }
                  },
                  "required": [
                      "result",
                      "withInterface"
                  ],
                  "additionalProperties": false
              }
          },
          "required": [
              "args",
              "boundary",
              "canisterId",
              "ingressExpiry",
              "message",
              "method",
              "requestId",
              "requestType",
              "sender"
          ],
          "additionalProperties": false
      },
      "DecodedResponse": {
          "anyOf": [
              {
                  "type": "object",
                  "properties": {
                      "status": {
                          "$ref": "#/definitions/QueryResponseStatus"
                      }
                  },
                  "required": [
                      "status"
                  ],
                  "additionalProperties": false
              },
              {
                  "type": "object",
                  "properties": {
                      "status": {
                          "$ref": "#/definitions/QueryResponseStatus"
                      },
                      "reply": {
                          "$ref": "#/definitions/CandidDecodeResult"
                      }
                  },
                  "required": [
                      "reply",
                      "status"
                  ],
                  "additionalProperties": false
              },
              {
                  "type": "object",
                  "properties": {
                      "status": {
                          "$ref": "#/definitions/RequestStatusResponseStatus"
                      }
                  },
                  "required": [
                      "status"
                  ],
                  "additionalProperties": false
              },
              {
                  "type": "object",
                  "properties": {
                      "status": {
                          "$ref": "#/definitions/RequestStatusResponseStatus"
                      },
                      "reply": {
                          "$ref": "#/definitions/CandidDecodeResult"
                      }
                  },
                  "required": [
                      "reply",
                      "status"
                  ],
                  "additionalProperties": false
              },
              {
                  "$ref": "#/definitions/RejectedResponse"
              }
          ]
      },
      "QueryResponseStatus": {
          "type": "string",
          "enum": [
              "replied",
              "rejected"
          ]
      },
      "CandidDecodeResult": {
          "type": "object",
          "properties": {
              "result": {},
              "withInterface": {
                  "type": "boolean"
              }
          },
          "required": [
              "result",
              "withInterface"
          ],
          "additionalProperties": false
      },
      "RequestStatusResponseStatus": {
          "type": "string",
          "enum": [
              "received",
              "processing",
              "replied",
              "rejected",
              "unknown",
              "done"
          ]
      },
      "RejectedResponse": {
          "type": "object",
          "properties": {
              "status": {
                  "$ref": "#/definitions/QueryResponseStatus"
              },
              "message": {
                  "type": "string"
              },
              "code": {
                  "type": "number"
              }
          },
          "required": [
              "code",
              "message",
              "status"
          ],
          "additionalProperties": false
      }
  }
}

=== Gekctek/ic-inspector/src/stubs/distrikt.getSelf.json
{
    "canister": {
      "identifier": "cea4l-ryaaa-aaaae-aaa6a-cai",
      "subnet": "shefu-t3kr5-t5q3w-mqmdq-jabyv-vyvtf-cyyey-3kmo4-toyln-emubw-4qe",
      "moduleHash": "cfbc6e42e626947d7cf5b7976d58422c0cdf3e5c04c4d1e31384343cb0b6145f",
      "controllers": [
        "hy3go-2qaaa-aaaae-aaabq-cai",
        "ins6m-vyaaa-aaaag-qabuq-cai",
        "xo4am-ryaaa-aaaai-qh4va-cai",
        "ho5nh-4iaaa-aaaaj-aaipa-cai",
        "vi77x-kqaaa-aaaak-aadyq-cai",
        "zheur-rqaaa-aaaal-qanoq-cai",
        "ljmf3-4iaaa-aaaan-qaafq-cai",
        "auw2h-nsumg-eq552-wz7u7-ckc2l-teo22-wjsea-gsprn-kk6ln-rofyd-bqe"
      ]
    },
    "caller": {
      "identifier": "2vxsx-fae",
      "isAnonymous": true
    },
    "method": {
      "name": "getSelf",
      "query": true
    },
    "timing": {
      "timestamp": "2022-08-16T04:13:42.248Z",
      "requestCount": 2,
      "durationMs": 168
    },
    "meta": {
      "originalRequestId": "0db643d1cacc1936b39f75ac3eeb15c18aa073dbc03eab8bdbc1c6223a1e7b64",
      "type": "query",
      "status": "rejected",
      "consensus": false,
      "verified": null,
      "boundary": {
        "_stub": true,
        "_url": true,
        "val": "https://boundary.ic0.app/api/v2/canister/cea4l-ryaaa-aaaae-aaa6a-cai/query"
      }
    },
    "requests": {
      "0db643d1cacc1936b39f75ac3eeb15c18aa073dbc03eab8bdbc1c6223a1e7b64": {
        "caller": {
          "identifier": "2vxsx-fae",
          "isAnonymous": true
        },
        "method": {
          "name": "getSelf",
          "query": true
        },
        "canister": {
          "identifier": "cea4l-ryaaa-aaaae-aaa6a-cai",
          "subnet": "shefu-t3kr5-t5q3w-mqmdq-jabyv-vyvtf-cyyey-3kmo4-toyln-emubw-4qe",
          "moduleHash": "cfbc6e42e626947d7cf5b7976d58422c0cdf3e5c04c4d1e31384343cb0b6145f",
          "controllers": [
            "hy3go-2qaaa-aaaae-aaabq-cai",
            "ins6m-vyaaa-aaaag-qabuq-cai",
            "xo4am-ryaaa-aaaai-qh4va-cai",
            "ho5nh-4iaaa-aaaaj-aaipa-cai",
            "vi77x-kqaaa-aaaak-aadyq-cai",
            "zheur-rqaaa-aaaal-qanoq-cai",
            "ljmf3-4iaaa-aaaan-qaafq-cai",
            "auw2h-nsumg-eq552-wz7u7-ckc2l-teo22-wjsea-gsprn-kk6ln-rofyd-bqe"
          ]
        },
        "meta": {
          "originalRequestId": "0db643d1cacc1936b39f75ac3eeb15c18aa073dbc03eab8bdbc1c6223a1e7b64",
          "requestId": "0db643d1cacc1936b39f75ac3eeb15c18aa073dbc03eab8bdbc1c6223a1e7b64",
          "type": "query",
          "boundary": {
            "_stub": true,
            "_url": true,
            "val": "https://boundary.ic0.app/api/v2/canister/cea4l-ryaaa-aaaae-aaa6a-cai/query"
          }
        },
        "timing": {
          "timestamp": "2022-08-16T04:13:42.416Z"
        },
        "request": {
          "boundary": {
            "_stub": true,
            "_url": true,
            "val": "https://boundary.ic0.app/api/v2/canister/cea4l-ryaaa-aaaae-aaa6a-cai/query"
          },
          "message": "0db643d1cacc1936b39f75ac3eeb15c18aa073dbc03eab8bdbc1c6223a1e7b64",
          "requestId": "0db643d1cacc1936b39f75ac3eeb15c18aa073dbc03eab8bdbc1c6223a1e7b64",
          "sender": {
            "_stub": true,
            "_principal": true,
            "val": "2vxsx-fae"
          },
          "requestType": "query",
          "ingressExpiry": {
            "_stub": true,
            "_bigint": true,
            "val": "1660623460053000000"
          },
          "canisterId": "cea4l-ryaaa-aaaae-aaa6a-cai",
          "method": "getSelf",
          "args": {
            "result": [],
            "withInterface": false
          }
        },
        "response": {
          "status": "rejected",
          "message": "IC0503: Canister cea4l-ryaaa-aaaae-aaa6a-cai trapped explicitly: Can't use the anonymous identity.",
          "code": 5
        }
      }
    }
  }

=== Gekctek/ic-inspector/src/stubs/distrikt.isFollowing.json
{
    "caller": {
      "identifier": "mr2uc-ob4zm-yik2z-vbsny-qsj2h-2np4i-drw75-7seho-a6jjx-5stsu-fqe",
      "isAnonymous": false
    },
    "canister": {
      "identifier": "cea4l-ryaaa-aaaae-aaa6a-cai",
      "subnet": "shefu-t3kr5-t5q3w-mqmdq-jabyv-vyvtf-cyyey-3kmo4-toyln-emubw-4qe",
      "moduleHash": "cfbc6e42e626947d7cf5b7976d58422c0cdf3e5c04c4d1e31384343cb0b6145f",
      "controllers": [
        "hy3go-2qaaa-aaaae-aaabq-cai",
        "ins6m-vyaaa-aaaag-qabuq-cai",
        "xo4am-ryaaa-aaaai-qh4va-cai",
        "ho5nh-4iaaa-aaaaj-aaipa-cai",
        "vi77x-kqaaa-aaaak-aadyq-cai",
        "zheur-rqaaa-aaaal-qanoq-cai",
        "ljmf3-4iaaa-aaaan-qaafq-cai",
        "auw2h-nsumg-eq552-wz7u7-ckc2l-teo22-wjsea-gsprn-kk6ln-rofyd-bqe"
      ]
    },
    "meta": {
      "originalRequestId": "26291801dcc2b40e471d23beeb558e7a468efcfe44e739b2f8948e91716acada",
      "type": "query",
      "status": "replied",
      "consensus": false,
      "verified": null,
      "boundary": {
        "_stub": true,
        "_url": true,
        "val": "https://boundary.ic0.app/api/v2/canister/cea4l-ryaaa-aaaae-aaa6a-cai/query"
      }
    },
    "method": {
      "name": "isFollowing",
      "query": true
    },
    "timing": {
      "timestamp": "2022-08-16T04:13:45.851Z",
      "requestCount": 1
    },
    "requests": {
      "26291801dcc2b40e471d23beeb558e7a468efcfe44e739b2f8948e91716acada": {
        "caller": {
          "identifier": "mr2uc-ob4zm-yik2z-vbsny-qsj2h-2np4i-drw75-7seho-a6jjx-5stsu-fqe",
          "isAnonymous": false
        },
        "method": {
          "name": "isFollowing",
          "query": true
        },
        "canister": {
          "identifier": "cea4l-ryaaa-aaaae-aaa6a-cai",
          "subnet": "shefu-t3kr5-t5q3w-mqmdq-jabyv-vyvtf-cyyey-3kmo4-toyln-emubw-4qe",
          "moduleHash": "cfbc6e42e626947d7cf5b7976d58422c0cdf3e5c04c4d1e31384343cb0b6145f",
          "controllers": [
            "hy3go-2qaaa-aaaae-aaabq-cai",
            "ins6m-vyaaa-aaaag-qabuq-cai",
            "xo4am-ryaaa-aaaai-qh4va-cai",
            "ho5nh-4iaaa-aaaaj-aaipa-cai",
            "vi77x-kqaaa-aaaak-aadyq-cai",
            "zheur-rqaaa-aaaal-qanoq-cai",
            "ljmf3-4iaaa-aaaan-qaafq-cai",
            "auw2h-nsumg-eq552-wz7u7-ckc2l-teo22-wjsea-gsprn-kk6ln-rofyd-bqe"
          ]
        },
        "meta": {
          "originalRequestId": "26291801dcc2b40e471d23beeb558e7a468efcfe44e739b2f8948e91716acada",
          "requestId": "26291801dcc2b40e471d23beeb558e7a468efcfe44e739b2f8948e91716acada",
          "type": "query",
          "boundary": {
            "_stub": true,
            "_url": true,
            "val": "https://boundary.ic0.app/api/v2/canister/cea4l-ryaaa-aaaae-aaa6a-cai/query"
          }
        },
        "timing": {
          "timestamp": "2022-08-16T04:13:45.851Z"
        },
        "request": {
          "boundary": {
            "_stub": true,
            "_url": true,
            "val": "https://boundary.ic0.app/api/v2/canister/cea4l-ryaaa-aaaae-aaa6a-cai/query"
          },
          "message": "26291801dcc2b40e471d23beeb558e7a468efcfe44e739b2f8948e91716acada",
          "requestId": "26291801dcc2b40e471d23beeb558e7a468efcfe44e739b2f8948e91716acada",
          "sender": {
            "_stub": true,
            "_principal": true,
            "val": "mr2uc-ob4zm-yik2z-vbsny-qsj2h-2np4i-drw75-7seho-a6jjx-5stsu-fqe"
          },
          "requestType": "query",
          "ingressExpiry": {
            "_stub": true,
            "_bigint": true,
            "val": "1660623463731000000"
          },
          "canisterId": "cea4l-ryaaa-aaaae-aaa6a-cai",
          "method": "isFollowing",
          "args": {
            "result": [
              {
                "_stub": true,
                "_bigint": true,
                "val": "177057365940518912"
              }
            ],
            "withInterface": false
          }
        },
        "response": {
          "status": "replied",
          "reply": {
            "result": [
              false
            ],
            "withInterface": false
          }
        }
      }
    }
  }
