=== Gekctek/ic-inspector/src/services/stubs/message.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/MessageEntry",
  "definitions": {
      "MessageEntry": {
          "type": "object",
          "properties": {
              "meta": {
                  "type": "object",
                  "properties": {
                      "originalRequestId": {
                          "$ref": "#/definitions/MessageId"
                      },
                      "type": {
                          "type": "string",
                          "enum": [
                              "update",
                              "query"
                          ]
                      },
                      "status": {
                          "$ref": "#/definitions/MessageStatus"
                      },
                      "consensus": {
                          "type": "boolean"
                      },
                      "verified": {
                          "type": "null"
                      },
                      "boundary": {
                        "$ref": "#/definitions/URL"
                      }
                  },
                  "required": [
                      "originalRequestId",
                      "type",
                      "status",
                      "consensus",
                      "verified",
                      "boundary"
                  ],
                  "additionalProperties": false
              },
              "canister": {
                  "type": "object",
                  "properties": {
                      "identifier": {
                          "type": "string"
                      },
                      "name": {
                          "type": "string"
                      },
                      "url": {
                          "type": "string"
                      },
                      "description": {
                          "type": "string"
                      },
                      "logoUrl": {
                          "type": "string"
                      },
                      "subnet": {
                          "type": "string"
                      },
                      "moduleHash": {
                          "type": "string"
                      },
                      "controllers": {
                          "type": "array",
                          "items": {
                              "type": "string"
                          }
                      }
                  },
                  "required": [
                      "identifier",
                      "subnet",
                      "moduleHash",
                      "controllers"
                  ],
                  "additionalProperties": false
              },
              "method": {
                  "type": "object",
                  "properties": {
                      "name": {
                          "type": "string"
                      },
                      "query": {
                          "type": "boolean"
                      }
                  },
                  "required": [
                      "name",
                      "query"
                  ],
                  "additionalProperties": false
              },
              "caller": {
                  "type": "object",
                  "properties": {
                      "identifier": {
                          "type": "string"
                      },
                      "isAnonymous": {
                          "type": "boolean"
                      }
                  },
                  "required": [
                      "identifier",
                      "isAnonymous"
                  ],
                  "additionalProperties": false
              },
              "timing": {
                  "type": "object",
                  "properties": {
                      "timestamp": {
                          "type": "string"
                      },
                      "durationMs": {
                          "type": "number"
                      },
                      "requestCount": {
                          "type": "number"
                      }
                  },
                  "required": [
                      "timestamp",
                      "requestCount"
                  ],
                  "additionalProperties": false
              },
              "requests": {
                  "type": "object",
                  "patternProperties": {
                      "^[a-fA-F0-9]+$": {
                      "type": "object",
                      "properties": {
                          "meta": {
                              "type": "object",
                              "properties": {
                                  "requestId": {
                                      "type": "string"
                                  },
                                  "originalRequestId": {
                                      "$ref": "#/definitions/MessageId"
                                  },
                                  "type": {
                                      "$ref": "#/definitions/RequestType"
                                  },
                                  "boundary": {
                                    "$ref": "#/definitions/URL"
                                  }
                              },
                              "required": [
                                  "requestId",
                                  "originalRequestId",
                                  "type",
                                  "boundary"
                              ],
                              "additionalProperties": false
                          },
                          "caller": {
                              "type": "object",
                              "properties": {
                                  "identifier": {
                                      "type": "string"
                                  },
                                  "isAnonymous": {
                                      "type": "boolean"
                                  }
                              },
                              "required": [
                                  "identifier",
                                  "isAnonymous"
                              ],
                              "additionalProperties": false
                          },
                          "canister": {
                              "type": "object",
                              "properties": {
                                  "identifier": {
                                      "type": "string"
                                  },
                                  "name": {
                                      "type": "string"
                                  },
                                  "url": {
                                      "type": "string"
                                  },
                                  "description": {
                                      "type": "string"
                                  },
                                  "logoUrl": {
                                      "type": "string"
                                  },
                                  "subnet": {
                                      "type": "string"
                                  },
                                  "moduleHash": {
                                      "type": "string"
                                  },
                                  "controllers": {
                                      "type": "array",
                                      "items": {
                                          "type": "string"
                                      }
                                  }
                              },
                              "required": [
                                  "identifier",
                                  "subnet",
                                  "moduleHash",
                                  "controllers"
                              ],
                              "additionalProperties": false
                          },
                          "method": {
                              "type": "object",
                              "properties": {
                                  "name": {
                                      "type": "string"
                                  },
                                  "query": {
                                      "type": "boolean"
                                  }
                              },
                              "required": [
                                  "name",
                                  "query"
                              ],
                              "additionalProperties": false
                          },
                          "timing": {
                              "type": "object",
                              "properties": {
                                  "timestamp": {
                                      "type": "string"
                                  },
                                  "durationMs": {
                                      "type": "number"
                                  }
                              },
                              "required": [
                                  "timestamp"
                              ],
                              "additionalProperties": false
                          },
                          "request": {
                              "$ref": "#/definitions/DecodedRequest"
                          },
                          "response": {
                              "$ref": "#/definitions/DecodedResponse"
                          }
                      },
                      "required": [
                          "meta",
                          "caller",
                          "canister",
                          "method",
                          "timing",
                          "request",
                          "response"
                      ],
                      "additionalProperties": false
                    }
                  }
              }
          },
          "required": [
              "meta",
              "canister",
              "method",
              "caller",
              "timing",
              "requests"
          ],
          "additionalProperties": false
      },
      "MessageId": {
          "type": "string"
      },
      "MessageStatus": {
          "type": "string",
          "enum": [
              "pending",
              "replied",
              "rejected"
          ]
      },
      "RequestType": {
          "type": "string",
          "enum": [
              "query",
              "call",
              "read_state"
          ]
      },
      "DecodedRequest": {
          "anyOf": [
              {
                  "type": "object",
                  "properties": {
                      "message": {
                          "type": "string"
                      },
                      "requestId": {
                          "type": "string"
                      },
                      "canisterId": {
                          "type": "string"
                      },
                      "method": {
                          "type": "string"
                      },
                      "sender": {
                          "$ref": "#/definitions/Principal"
                      },
                      "requestType": {
                          "$ref": "#/definitions/RequestType"
                      },
                      "ingressExpiry": {
                          "$ref": "#/definitions/Expiry"
                      },
                      "boundary": {
                        "$ref": "#/definitions/URL"
                      },
                      "paths": {
                          "type": "array",
                          "items": {
                              "type": "array",
                              "items": {
                                  "type": "object",
                                  "patternProperties": {
                                      "[0-9]+": {
                                          "type": "number"
                                      }
                                  }
                              }
                          }
                      }
                  },
                  "required": [
                      "boundary",
                      "canisterId",
                      "ingressExpiry",
                      "message",
                      "method",
                      "paths",
                      "requestId",
                      "requestType",
                      "sender"
                  ],
                  "additionalProperties": false
              },
              {
                  "$ref": "#/definitions/DecodedReadRequest"
              }
          ]
      },
      "Principal": {
          "type": "object",
          "properties": {
            "_stub": { "type": "boolean" },
            "_principal": { "type": "boolean" },
            "val": { "type": "string" }
          },
          "required": [ "_stub", "_principal", "val"]
        },
      "Expiry": {
          "type": "object",
          "properties": {
            "_stub": { "type": "boolean" },
            "_bigint": { "type": "boolean" },
            "val": { "type": "string" }
          },
          "required": [ "_stub", "_bigint", "val" ]
        },
      "URL": {
          "type": "object",
          "properties": {
            "_stub": { "type": "boolean" },
            "_url": { "type": "boolean" },
            "val": { "type": "string" }
          },
          "required": [ "_stub", "_url", "val" ]
        },
      "DecodedReadRequest": {
          "type": "object",
          "properties": {
              "message": {
                  "type": "string"
              },
              "requestId": {
                  "type": "string"
              },
              "canisterId": {
                  "type": "string"
              },
              "method": {
                  "type": "string"
              },
              "sender": {
                  "$ref": "#/definitions/Principal"
              },
              "requestType": {
                  "$ref": "#/definitions/RequestType"
              },
              "ingressExpiry": {
                  "$ref": "#/definitions/Expiry"
              },
              "boundary": {
                "$ref": "#/definitions/URL"
              },
              "args": {
                  "type": "object",
                  "properties": {
                      "result": {},
                      "withInterface": {
                          "type": "boolean"
                      }
                  },
                  "required": [
                      "result",
                      "withInterface"
                  ],
                  "additionalProperties": false
              }
          },
          "required": [
              "args",
              "boundary",
              "canisterId",
              "ingressExpiry",
              "message",
              "method",
              "requestId",
              "requestType",
              "sender"
          ],
          "additionalProperties": false
      },
      "DecodedResponse": {
          "anyOf": [
              {
                  "type": "object",
                  "properties": {
                      "status": {
                          "$ref": "#/definitions/QueryResponseStatus"
                      }
                  },
                  "required": [
                      "status"
                  ],
                  "additionalProperties": false
              },
              {
                  "type": "object",
                  "properties": {
                      "status": {
                          "$ref": "#/definitions/QueryResponseStatus"
                      },
                      "reply": {
                          "$ref": "#/definitions/CandidDecodeResult"
                      }
                  },
                  "required": [
                      "reply",
                      "status"
                  ],
                  "additionalProperties": false
              },
              {
                  "type": "object",
                  "properties": {
                      "status": {
                          "$ref": "#/definitions/RequestStatusResponseStatus"
                      }
                  },
                  "required": [
                      "status"
                  ],
                  "additionalProperties": false
              },
              {
                  "type": "object",
                  "properties": {
                      "status": {
                          "$ref": "#/definitions/RequestStatusResponseStatus"
                      },
                      "reply": {
                          "$ref": "#/definitions/CandidDecodeResult"
                      }
                  },
                  "required": [
                      "reply",
                      "status"
                  ],
                  "additionalProperties": false
              },
              {
                  "$ref": "#/definitions/RejectedResponse"
              }
          ]
      },
      "QueryResponseStatus": {
          "type": "string",
          "enum": [
              "replied",
              "rejected"
          ]
      },
      "CandidDecodeResult": {
          "type": "object",
          "properties": {
              "result": {},
              "withInterface": {
                  "type": "boolean"
              }
          },
          "required": [
              "result",
              "withInterface"
          ],
          "additionalProperties": false
      },
      "RequestStatusResponseStatus": {
          "type": "string",
          "enum": [
              "received",
              "processing",
              "replied",
              "rejected",
              "unknown",
              "done"
          ]
      },
      "RejectedResponse": {
          "type": "object",
          "properties": {
              "status": {
                  "$ref": "#/definitions/QueryResponseStatus"
              },
              "message": {
                  "type": "string"
              },
              "code": {
                  "type": "number"
              }
          },
          "required": [
              "code",
              "message",
              "status"
          ],
          "additionalProperties": false
      }
  }
}

=== Gekctek/ic-inspector/src/repositories/stubs/metascore.getScoreCount.json
{
    "caller": {
      "identifier": "2vxsx-fae",
      "isAnonymous": true
    },
    "canister": {
      "identifier": "tzvxm-jqaaa-aaaaj-qabga-cai",
      "subnet": "jtdsg-3h6gi-hs7o5-z2soi-43w3z-soyl3-ajnp3-ekni5-sw553-5kw67-nqe",
      "moduleHash": "5ac0453ff6787f7c5670e8bb55b5ddeb54ae6cec07ac1e9a95aee86b44988c04",
      "controllers": [
        "tmsgb-iyaaa-aaaaj-qabfq-cai"
      ]
    },
    "meta": {
      "originalRequestId": "56eb04efba57477f0829644e3a2e7bd75e39afa37f8393248fbf5f67dda09ad5",
      "type": "query",
      "status": "replied",
      "consensus": false,
      "verified": null,
      "boundary": {
        "_stub": true,
        "_url": true,
        "val": "https://raw.ic0.app/api/v2/canister/tzvxm-jqaaa-aaaaj-qabga-cai/query"
      }
    },
    "method": {
      "name": "getScoreCount",
      "query": true
    },
    "timing": {
      "timestamp": "2022-08-15T21:05:13.257Z",
      "requestCount": 1
    },
    "requests": {
      "56eb04efba57477f0829644e3a2e7bd75e39afa37f8393248fbf5f67dda09ad5": {
        "caller": {
          "identifier": "2vxsx-fae",
          "isAnonymous": true
        },
        "method": {
          "name": "getScoreCount",
          "query": true
        },
        "canister": {
          "identifier": "tzvxm-jqaaa-aaaaj-qabga-cai",
          "subnet": "jtdsg-3h6gi-hs7o5-z2soi-43w3z-soyl3-ajnp3-ekni5-sw553-5kw67-nqe",
          "moduleHash": "5ac0453ff6787f7c5670e8bb55b5ddeb54ae6cec07ac1e9a95aee86b44988c04",
          "controllers": [
            "tmsgb-iyaaa-aaaaj-qabfq-cai"
          ]
        },
        "meta": {
          "originalRequestId": "56eb04efba57477f0829644e3a2e7bd75e39afa37f8393248fbf5f67dda09ad5",
          "requestId": "56eb04efba57477f0829644e3a2e7bd75e39afa37f8393248fbf5f67dda09ad5",
          "type": "query",
          "boundary": {
            "_stub": true,
            "_url": true,
            "val": "https://raw.ic0.app/api/v2/canister/tzvxm-jqaaa-aaaaj-qabga-cai/query"
          }
        },
        "timing": {
          "timestamp": "2022-08-15T21:05:13.257Z"
        },
        "request": {
          "boundary": {
            "_stub": true,
            "_url": true,
            "val": "https://raw.ic0.app/api/v2/canister/tzvxm-jqaaa-aaaaj-qabga-cai/query"
          },
          "message": "56eb04efba57477f0829644e3a2e7bd75e39afa37f8393248fbf5f67dda09ad5",
          "requestId": "56eb04efba57477f0829644e3a2e7bd75e39afa37f8393248fbf5f67dda09ad5",
          "sender": {
            "_stub": true,
            "_principal": true,
            "val": "2vxsx-fae"
          },
          "requestType": "query",
          "ingressExpiry": {
            "_stub": true,
            "_bigint": true,
            "val": "1660597749791000000"
          },
          "canisterId": "tzvxm-jqaaa-aaaaj-qabga-cai",
          "method": "getScoreCount",
          "args": {
            "result": null,
            "withInterface": true
          }
        },
        "response": {
          "status": "replied",
          "reply": {
            "result": {
              "_stub": true,
              "_bigint": true,
              "val": "180"
            },
            "withInterface": true
          }
        }
      }
    }
}

=== Gekctek/ic-inspector/src/repositories/stubs/dscvr.get_self.json
{
    "caller": {
      "identifier": "fgkxo-klvdw-vb3ft-2oslc-jwn5a-nyqvo-rtwwi-6rg4h-m4qu7-kffpf-tae",
      "isAnonymous": false
    },
    "canister": {
      "identifier": "h2bch-3yaaa-aaaab-qaama-cai",
      "subnet": "pae4o-o6dxf-xki7q-ezclx-znyd6-fnk6w-vkv5z-5lfwh-xym2i-otrrw-fqe",
      "moduleHash": "d4c8ed2b427e9bf35bec2243e6fab5a7ed7a2d528bb601e959ceb7efc8b0ba34",
      "controllers": [
        "g6mnv-cyaaa-aaaab-qaaka-cai"
      ]
    },
    "meta": {
      "originalRequestId": "77a4c1083ca9d3932b3c0dce20cbd729427fd40125802cd5fcdf1d1e8635909d",
      "type": "query",
      "status": "replied",
      "consensus": false,
      "verified": null,
      "boundary": {
        "_stub": true,
        "_url": true,
        "val": "https://ic0.app/api/v2/canister/h2bch-3yaaa-aaaab-qaama-cai/query"
      }
    },
    "method": {
      "name": "get_self",
      "query": true
    },
    "timing": {
      "timestamp": "2022-08-16T03:47:15.853Z",
      "requestCount": 1
    },
    "requests": {
      "77a4c1083ca9d3932b3c0dce20cbd729427fd40125802cd5fcdf1d1e8635909d": {
        "caller": {
          "identifier": "fgkxo-klvdw-vb3ft-2oslc-jwn5a-nyqvo-rtwwi-6rg4h-m4qu7-kffpf-tae",
          "isAnonymous": false
        },
        "method": {
          "name": "get_self",
          "query": true
        },
        "canister": {
          "identifier": "h2bch-3yaaa-aaaab-qaama-cai",
          "subnet": "pae4o-o6dxf-xki7q-ezclx-znyd6-fnk6w-vkv5z-5lfwh-xym2i-otrrw-fqe",
          "moduleHash": "d4c8ed2b427e9bf35bec2243e6fab5a7ed7a2d528bb601e959ceb7efc8b0ba34",
          "controllers": [
            "g6mnv-cyaaa-aaaab-qaaka-cai"
          ]
        },
        "meta": {
          "originalRequestId": "77a4c1083ca9d3932b3c0dce20cbd729427fd40125802cd5fcdf1d1e8635909d",
          "requestId": "77a4c1083ca9d3932b3c0dce20cbd729427fd40125802cd5fcdf1d1e8635909d",
          "type": "query",
          "boundary": {
            "_stub": true,
            "_url": true,
            "val": "https://ic0.app/api/v2/canister/h2bch-3yaaa-aaaab-qaama-cai/query"
          }
        },
        "timing": {
          "timestamp": "2022-08-16T03:47:15.853Z"
        },
        "request": {
          "boundary": {
            "_stub": true,
            "_url": true,
            "val": "https://ic0.app/api/v2/canister/h2bch-3yaaa-aaaab-qaama-cai/query"
          },
          "message": "77a4c1083ca9d3932b3c0dce20cbd729427fd40125802cd5fcdf1d1e8635909d",
          "requestId": "77a4c1083ca9d3932b3c0dce20cbd729427fd40125802cd5fcdf1d1e8635909d",
          "sender": {
            "_stub": true,
            "_principal": true,
            "val": "fgkxo-klvdw-vb3ft-2oslc-jwn5a-nyqvo-rtwwi-6rg4h-m4qu7-kffpf-tae"
          },
          "requestType": "query",
          "ingressExpiry": {
            "_stub": true,
            "_bigint": true,
            "val": "1660621871152000000"
          },
          "canisterId": "h2bch-3yaaa-aaaab-qaama-cai",
          "method": "get_self",
          "args": {
            "result": [],
            "withInterface": false
          }
        },
        "response": {
          "status": "replied",
          "reply": {
            "result": [
              {
                "_100394802_": "happy",
                "_142895325_": [
                  {
                    "_23515_": {
                      "_stub": true,
                      "_principal": true,
                      "val": "fgkxo-klvdw-vb3ft-2oslc-jwn5a-nyqvo-rtwwi-6rg4h-m4qu7-kffpf-tae"
                    },
                    "_4896968_": "",
                    "_357270062_": false,
                    "_381635694_": {
                      "_stub": true,
                      "_bigint": true,
                      "val": "0"
                    },
                    "_552306198_": "jbdr",
                    "_1010338175_": [],
                    "_1311134999_": {
                      "_stub": true,
                      "_bigint": true,
                      "val": "0"
                    },
                    "_1779848746_": {
                      "_stub": true,
                      "_bigint": true,
                      "val": "1660380696341855921"
                    },
                    "_2169702505_": "",
                    "_2425577243_": false,
                    "_3048521879_": {
                      "_1869947023_": {
                        "_stub": true,
                        "_principal": true,
                        "val": "fgkxo-klvdw-vb3ft-2oslc-jwn5a-nyqvo-rtwwi-6rg4h-m4qu7-kffpf-tae"
                      },
                      "_2478603148_": false
                    }
                  }
                ],
                "_1365803947_": [],
                "_2584819143_": ""
              }
            ],
            "withInterface": false
          }
        }
      }
    }
  }
